### ISSUE TITLE
Revert PR #1

### ISSUE THREAD

**Issue by le717** [mathom/LIME#2]
I am so sorry, Matt.

I was working with LIME again today (someone asked me to replace the command-line parameter with a dialog box, which I did), and I realized that I submitted a _completely_ broken [PR](1). I had gotten my Python versions mixed up, and testing LIME on Python 2 instead of 3, like I had thought I was doing. I actually broke the script in the PR: the import is wrong, and it throws an assert error on Python 3.

Since I feel like I need to correct this issue I created, here is a fixed version. It is Python 2 only, just like before, but I've added the message changes I made earlier. I can't do another PR, for GitHub wants to merge other files (like the aforementioned file dialog).

Please accept this commit, and I am so, so sorry about this. I test my code so many times before I commit it, let alone before submitting a PR, so I feel really bad about this.
- [Fixed script](https://github.com/le717/LIME/blob/f92c6e1772609ab5c61d362259e9750ec9541181/lime.py)

**Comment by mathom** [comment]
Hey, no problem. I really appreciate your interest in the project.

I was the one that merged after only testing it on python 2. Just submit another PR and I'll be sure to test both this time! :grinning:

**Comment by mathom** [comment]
To make the PR you will want to checkout a copy of my master in a new branch. Say you have a remote called "matt" that points to the upstream repo. You can just do this:

```
git fetch matt
git checkout -b fix_pr_1 matt/master
```

Then just drop your script on top. Git should show your changes and let you commit them. Then all you have to do is push them up to github and create another PR. Let me know if you need any further help!

**Comment by le717** [comment]
Alright. I'll get on that.

Just a question: Would you rather I try to make a Python 2/3 port of the command-line LIME, or should I try to do it with my modified [UI one?](https://github.com/le717/LIME/blob/master/limeui.py) It would be a bit harder with the UI, since the file selection dialog box was renamed in Py 3, but I could try to get it working. I can't do a full GUI,  because I've yet to learn that code, but I don't think that is needed.

 Either way, I'll work.

**Comment by mathom** [comment]
I actually haven't seen your UI yet. Very interesting! I was actually playing with that idea a bit but I'm mostly working on a more general extractor (for images, etc) in the `rewrite` branch. It's very early right now but I hope to get some more work done soon.

If you could make the UI one skip the Tk stuff if you supply command line arguments I'd be glad to merge it in over the current setup. Though for right now just a PR against the regular one is fine.

If you need any help setting up branches or the sort in git let me know. Thanks! :+1:
