### ISSUE TITLE
LIME re-write doesn't work.

### ISSUE THREAD

**Issue by rioforce** [mathom/LIME#3]
Hello, I was trying the LIME re-write branch, but it always ends in an error and won't extract. The original branch works, but crashes on a helicopter video. Is there any way to fix the crash? I really like your program! :D

**Comment by mathom** [comment]
Hey, thank you for the interest! The rewrite isn't quite ready yet. When I get it in usable shape I'll merge it over master.

Can you paste me the program output and filename you ran it on? I might be able to fix the main branch in the meantime.

**Comment by rioforce** [comment]
![lime error](https://f.cloud.github.com/assets/3674297/568831/0ade008e-c6e7-11e2-996c-eede6fb2cc2d.png)
Hope this helps. I read somewhere on the internet that the movies are a Smacker format if that helps. :) (http://www.radgametools.com/smkmain.htm)

**Comment by mathom** [comment]
Ah my tool only extracts audio tracks. My main branch just does a stupid hack to find wav files in the package and rip them :grinning:  The rewrite should be able to extract any format when I'm finished. I'd be happy to debug that sample width issue for you though.

**Comment by rioforce** [comment]
If that will let it skip the video and finish extracting, that would be great! Thanks a lot! :D

**Comment by mathom** [comment]
I just set it up to skip files with weird formats in https://github.com/mathom/LIME/commit/2995fe445b15960cfba299a08b4b195a5d3715e4. Looks like it's just the build movies - they probably have some extra info that isn't on the regular waves. Let me know if you have any other problems!

**Comment by rioforce** [comment]
Thanks a lot! It works great!

(Any idea when the re-write will be done? ;) )

**Comment by rioforce** [comment]
Not to tell you how to do you job or anything, but is it possible to just extract the files raw, so it doesn't search for audio, or do you have to know all the formats?

Thanks. :)

**Comment by mathom** [comment]
Probably a while yet. The files contained in those RIFFs are nonstandard too so they may not actually be usable once extracted. You can examine the SI files with a hex editor to try to figure out what's contained in there.
